### Context root path ########
server: 
  servlet:
    context-path: /api/auth
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:hankkiauth
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /db/hankkiauth
  jpa: 
    generate-ddl: true
    show-sql: true
    hibernate: 
      ddl-auto: create
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl