### Context root path ########
server: 
  servlet:
    context-path: /api/auth
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource  
    url: jdbc:mariadb://localhost:3307/hankkiauth
    hikari:
      username: hankkiauth
      password: hankkiauth
      driver-class-name: org.mariadb.jdbc.Driver
      maximum-pool-size: 10
  jpa: 
    generate-ddl: true
    show-sql: true
    hibernate: 
      ddl-auto: create
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl