### Context root path ########
jwt:
  secret: javainuse
# server: 
#   servlet:
#     context-path: /api/auth
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:hankkiauth
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /db/hankkiauth
  jpa: 
    generate-ddl: true
    show-sql: true
    hibernate: 
      ddl-auto: create
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
zuul:
  routes:
    material:
      path: /api/materials/**
      url: http://hankki-material:8081/api/materials
    myrecipe:
      path: /api/myrecipes/**
      url: http://hankki-myrecipe:8082/api/myrecipes
    recipe:
      path: /api/recipes/**
      url: http://hankki-recipe:8083/api/recipes  
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:hankkiauth
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /db/hankkiauth
  jpa: 
    generate-ddl: true
    show-sql: true
    hibernate: 
      ddl-auto: create
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
zuul:
  routes:
    material:
      path: /api/materials/**
      url: http://hankki-material:8081/api/materials
    myrecipe:
      path: /api/myrecipes/**
      url: http://hankki-myrecipe:8082/api/myrecipes
    recipe:
      path: /api/recipes/**
      url: http://hankki-recipe:8083/api/recipes  