### Context root path ########
server: 
  port: 8082
  context-path: /api/myrecipes
  servlet:
    context-path: /api/myrecipes
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:hankkimyrecipe
    driverClassName: org.h2.Driver
    data: classpath:sql/data-H2.sql
  h2:
    console:
      enabled: true
      path: /db/hankkimyrecipe
  jpa: 
    generate-ddl: true
    show-sql: true
    hibernate: 
      ddl-auto: create
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl