kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: hankki-recipe
spec:
  replicas: 1
  template:
    metadata:
      name: hankki-recipe
      labels:
        app: hankki-recipe
    spec:
      containers:
      - name: hankki-recipe
        image: gcr.io/eunbyul/hankki-recipe:v1
        imagePullPolicy: Always
        command: ["java", "-jar", "hankki-recipe-0.0.1-SNAPSHOT.jar"]
        ports:
        - name: hankki-recipe
          containerPort: 8083

