apiVersion: v1
kind: Service
metadata:
  name: hankki-myrecipe
spec:
  selector:
    app: hankki-myrecipe
  type: NodePort
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: 8082
