apiVersion: v1
kind: Service
metadata:
  name: hankki-myrecipe
spec:
  selector:
    app: hankki-myrecipe
  #type: NodePort
  ##확인을 위해 임시설정
  type: LoadBalancer
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: 8082
