apiVersion: v1
kind: Service
metadata:
  name: hankki-auth
spec:
  selector:
    app: hankki-auth
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
