apiVersion: v1
kind: Service
metadata:
  name: hankki-material
spec:
  selector:
    app: hankki-material
  #type: NodePort
  ##확인을 위해 임시설정
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
