apiVersion: v1
kind: Service
metadata:
  name: hankki-recipe
spec:
  selector:
    app: hankki-recipe
  #type: NodePort
  ##확인을 위해 임시설정
  type: LoadBalancer
  ports:
    - name: http
      port: 8083
      protocol: TCP
      targetPort: 8083
