### Context root path ########
server: 
  port: 8083
  context-path: /api/recipes
  servlet:
    context-path: /api/recipes
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:hankkirecipe
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /db/hankkirecipe
  jpa: 
    generate-ddl: true
    show-sql: true
    hibernate: 
      ddl-auto: create
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl